"""add_patient_cache_fields

Revision ID: b9fc4472a124
Revises: 5ca6d34654f6
Create Date: 2026-07-23 17:08:22.689484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9fc4472a124'
down_revision: Union[str, Sequence[str], None] = '5ca6d34654f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_profiles', sa.Column('cached_case_history', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('case_history_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_profiles', 'case_history_updated_at')
    op.drop_column('patient_profiles', 'cached_case_history')
    # ### end Alembic commands ###
