"""move hospital_id to users table

Revision ID: ba78ba9e776a
Revises: c8f4dabe9dfe
Create Date: 2026-07-21 12:23:07.158587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba78ba9e776a'
down_revision: Union[str, Sequence[str], None] = 'c8f4dabe9dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('doctor_profiles_hospital_id_fkey', 'doctor_profiles', type_='foreignkey')
    op.drop_column('doctor_profiles', 'hospital_id')
    op.add_column('users', sa.Column('hospital_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'hospitals', ['hospital_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'hospital_id')
    op.add_column('doctor_profiles', sa.Column('hospital_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('doctor_profiles_hospital_id_fkey', 'doctor_profiles', 'hospitals', ['hospital_id'], ['id'])
    # ### end Alembic commands ###
