"""Rollback Phase 2 and simplify

Revision ID: d84f65e65b51
Revises: d990c9419a8a
Create Date: 2026-07-21 13:05:21.090690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd84f65e65b51'
down_revision: Union[str, Sequence[str], None] = 'd990c9419a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laboratories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('license_number', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laboratories_id'), 'laboratories', ['id'], unique=False)
    op.create_index(op.f('ix_laboratories_name'), 'laboratories', ['name'], unique=False)
    op.create_table('pharmacies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('license_number', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacies_id'), 'pharmacies', ['id'], unique=False)
    op.create_index(op.f('ix_pharmacies_name'), 'pharmacies', ['name'], unique=False)
    op.create_table('doctor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('license_number', sa.String(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('qualification', sa.String(), nullable=True),
    sa.Column('consultation_fee', sa.Integer(), nullable=True),
    sa.Column('availability', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_doctor_profiles_id'), 'doctor_profiles', ['id'], unique=False)
    op.drop_index('ix_employee_profiles_id', table_name='employee_profiles')
    op.drop_table('employee_profiles')
    
    # Drop constraint first
    op.drop_constraint('departments_branch_id_fkey', 'departments', type_='foreignkey')
    
    op.drop_index('ix_branches_id', table_name='branches')
    op.drop_index('ix_branches_name', table_name='branches')
    op.drop_table('branches')
    
    op.add_column('departments', sa.Column('hospital_id', sa.Integer(), nullable=True))
    op.add_column('departments', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'departments', 'hospitals', ['hospital_id'], ['id'])
    op.drop_column('departments', 'branch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.create_foreign_key('departments_branch_id_fkey', 'departments', 'branches', ['branch_id'], ['id'])
    op.drop_column('departments', 'is_active')
    op.drop_column('departments', 'hospital_id')
    op.create_table('branches',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('branches_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name='branches_hospital_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='branches_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_branches_name', 'branches', ['name'], unique=False)
    op.create_index('ix_branches_id', 'branches', ['id'], unique=False)
    op.create_table('employee_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employee_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('designation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('specialization', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('license_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='employee_profiles_department_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='employee_profiles_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='employee_profiles_pkey'),
    sa.UniqueConstraint('user_id', name='employee_profiles_user_id_key')
    )
    op.create_index('ix_employee_profiles_id', 'employee_profiles', ['id'], unique=False)
    op.drop_index(op.f('ix_doctor_profiles_id'), table_name='doctor_profiles')
    op.drop_table('doctor_profiles')
    op.drop_index(op.f('ix_pharmacies_name'), table_name='pharmacies')
    op.drop_index(op.f('ix_pharmacies_id'), table_name='pharmacies')
    op.drop_table('pharmacies')
    op.drop_index(op.f('ix_laboratories_name'), table_name='laboratories')
    op.drop_index(op.f('ix_laboratories_id'), table_name='laboratories')
    op.drop_table('laboratories')
    # ### end Alembic commands ###
