"""Phase 3 and 4 Redesign

Revision ID: cb291c94a7e4
Revises: d84f65e65b51
Create Date: 2026-07-21 13:12:13.943728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb291c94a7e4'
down_revision: Union[str, Sequence[str], None] = 'd84f65e65b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('file_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_records_filename'), 'file_records', ['filename'], unique=False)
    op.create_index(op.f('ix_file_records_id'), 'file_records', ['id'], unique=False)
    op.add_column('departments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('departments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('departments', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('departments', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('hospitals', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('hospitals', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('hospitals', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('hospitals', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('hospitals', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hospitals', 'organizations', ['organization_id'], ['id'])
    op.add_column('laboratories', sa.Column('hospital_id', sa.Integer(), nullable=True))
    op.add_column('laboratories', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('laboratories', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('laboratories', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('laboratories', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'laboratories', 'hospitals', ['hospital_id'], ['id'])
    op.add_column('patient_profiles', sa.Column('hospital_id', sa.Integer(), nullable=True))
    op.add_column('patient_profiles', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('dob', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('address', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('profile_photo', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('emergency_contact_relation', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('organ_donor', sa.Boolean(), nullable=True))
    op.add_column('patient_profiles', sa.Column('known_allergies', sa.JSON(), nullable=True))
    op.add_column('patient_profiles', sa.Column('chronic_diseases', sa.JSON(), nullable=True))
    op.add_column('patient_profiles', sa.Column('current_medications', sa.JSON(), nullable=True))
    op.add_column('patient_profiles', sa.Column('past_surgeries', sa.JSON(), nullable=True))
    op.add_column('patient_profiles', sa.Column('status', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('allow_doctor_access', sa.Boolean(), nullable=True))
    op.add_column('patient_profiles', sa.Column('allow_hospital_access', sa.Boolean(), nullable=True))
    op.add_column('patient_profiles', sa.Column('emergency_access', sa.Boolean(), nullable=True))
    op.add_column('patient_profiles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('patient_profiles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('patient_profiles', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('patient_profiles', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patient_profiles', 'hospitals', ['hospital_id'], ['id'])
    op.drop_column('patient_profiles', 'personal_details')
    op.drop_column('patient_profiles', 'allergies')
    op.drop_column('patient_profiles', 'medical_history')
    op.drop_column('patient_profiles', 'lifestyle')
    op.drop_column('patient_profiles', 'family_history')
    op.add_column('pharmacies', sa.Column('hospital_id', sa.Integer(), nullable=True))
    op.add_column('pharmacies', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('pharmacies', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('pharmacies', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('pharmacies', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pharmacies', 'hospitals', ['hospital_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pharmacies', type_='foreignkey')
    op.drop_column('pharmacies', 'updated_by')
    op.drop_column('pharmacies', 'created_by')
    op.drop_column('pharmacies', 'updated_at')
    op.drop_column('pharmacies', 'created_at')
    op.drop_column('pharmacies', 'hospital_id')
    op.add_column('patient_profiles', sa.Column('family_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('patient_profiles', sa.Column('lifestyle', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('patient_profiles', sa.Column('medical_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('patient_profiles', sa.Column('allergies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('patient_profiles', sa.Column('personal_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'patient_profiles', type_='foreignkey')
    op.drop_column('patient_profiles', 'updated_by')
    op.drop_column('patient_profiles', 'created_by')
    op.drop_column('patient_profiles', 'updated_at')
    op.drop_column('patient_profiles', 'created_at')
    op.drop_column('patient_profiles', 'emergency_access')
    op.drop_column('patient_profiles', 'allow_hospital_access')
    op.drop_column('patient_profiles', 'allow_doctor_access')
    op.drop_column('patient_profiles', 'status')
    op.drop_column('patient_profiles', 'past_surgeries')
    op.drop_column('patient_profiles', 'current_medications')
    op.drop_column('patient_profiles', 'chronic_diseases')
    op.drop_column('patient_profiles', 'known_allergies')
    op.drop_column('patient_profiles', 'organ_donor')
    op.drop_column('patient_profiles', 'emergency_contact_relation')
    op.drop_column('patient_profiles', 'profile_photo')
    op.drop_column('patient_profiles', 'address')
    op.drop_column('patient_profiles', 'gender')
    op.drop_column('patient_profiles', 'dob')
    op.drop_column('patient_profiles', 'full_name')
    op.drop_column('patient_profiles', 'hospital_id')
    op.drop_constraint(None, 'laboratories', type_='foreignkey')
    op.drop_column('laboratories', 'updated_by')
    op.drop_column('laboratories', 'created_by')
    op.drop_column('laboratories', 'updated_at')
    op.drop_column('laboratories', 'created_at')
    op.drop_column('laboratories', 'hospital_id')
    op.drop_constraint(None, 'hospitals', type_='foreignkey')
    op.drop_column('hospitals', 'updated_by')
    op.drop_column('hospitals', 'created_by')
    op.drop_column('hospitals', 'updated_at')
    op.drop_column('hospitals', 'created_at')
    op.drop_column('hospitals', 'organization_id')
    op.drop_column('doctor_profiles', 'updated_by')
    op.drop_column('doctor_profiles', 'created_by')
    op.drop_column('doctor_profiles', 'updated_at')
    op.drop_column('doctor_profiles', 'created_at')
    op.drop_column('departments', 'updated_by')
    op.drop_column('departments', 'created_by')
    op.drop_column('departments', 'updated_at')
    op.drop_column('departments', 'created_at')
    op.drop_index(op.f('ix_file_records_id'), table_name='file_records')
    op.drop_index(op.f('ix_file_records_filename'), table_name='file_records')
    op.drop_table('file_records')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
